version: "3.9"

services:
  absensi_app:
    image: adipurnomo/absensi_app:0.0.1
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    # depends_on:
    #   - db
  
  # db:
  #   container_name: db
  #   image: mysql:8.0
  #   cap_add:
  #     - SYS_NICE
  #   ports:
  #     - "3306:3306"
  #   environment:
  #     MYSQL_DATABASE: absensi_app
  #     MYSQL_USER: root
  #     MYSQL_PASSWORD: root
  #     MYSQL_ROOT_PASSWORD: root
  #   command: --default-authentication-plugin=mysql_native_password
  #   volumes:
  #   # - db:/var/lib/mysql
  #   - "./mysqldata/absensi_app.sql:/docker-entrypoint-initdb.d/1.sql"

# volumes:
#   mysqldata: {}
    
